In [33]:
from IPython.display import HTML

HTML('''<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
<form action="javascript:code_toggle()"><input type="submit" value="Click here to toggle on/off the raw code."></form>''')

## Empirical Practice of Difference-in-Differences 

### Callaway and Sant'Anna(2020)

To get more familiar with the recent methodological studies in dif-in-diff(DID) methods, I attempt to replicate [Callaway and Sant'Anna(2020)](https://pedrohcgs.github.io/files/Callaway_SantAnna_2020.pdf)(Hereafter CS). CS proposes a DID estimator for research designs with multiple time periods and units particularly when units are being treated at staggered time periods. As it is well-known causal inference method, a standard did design includes only two time periods and two units. For example please see the famous example of Card and Kruger Wage Study(1994) in 2x2 table below.

   |      | Pre | Post | Difference |
   | --- | --- | --- | --- |
   |New Jersey     |  20.44 | 21.03 | 0.59 |
   |Pennsylvania     |  23.33 | 21.17 | - 2.16 |
   |**Difference**      | - 2.89 |  -0.14 | 2.75 |

A standard 2x2 DID method is not applicable for cases such as Medicaid expansion. The Affordable Care Act (ACA) mandated to expand the elibility of Medicaid so the number of low-income Americans with health insurance increases. When Medicaid expansion took effect in 2014, 27 seven states adopted the expansion that year. As of 2021 the total number of states with Medicaid expansion is 39. Only 12 states have not adopted Medicaid expansion yet so far. Different expansion year makes the data perfect for a DID analysis with multiple time periods and groups. 

I apply CS method in this post using Medicaid expansion data which I extracted from American Community Survey (ACS) and [Kaiser Family Foundation website](https://www.kff.org/medicaid/issue-brief/status-of-state-medicaid-expansion-decisions-interactive-map/). The data includes median income level, uninsured and unemployment rate at the county level from 2011 to 2019. For the sake of transparency, I am sharing the data at [the this link](https://raw.githubusercontent.com/mehmet-sari/Exercises_Applications/main/medicaidexpansion.csv).

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression as lr
import statsmodels.formula.api as smf
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

#pd.set_option('display.max_rows', 500)
%load_ext rpy2.ipython

#### Data Summary 
The next two outputs show the data and summary statistics of uninsured rate, median income level, and unemployment rate.

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/mehmet-sari/Exercises_Applications/main/medicaidexpansion.csv", encoding='latin-1')
df['AdoptedYear'] = df['AdoptedYear'].replace([2020, 2021],0)
df.head(10)

,State,id,unemployment,median_income,uninsured,year,County,MedicaidStatus,AdoptedYear,SID
0,Alabama,0500000US01003,5.6,50900,12.0,2011,Baldwin County,Not Adopted,0,1
1,Alabama,0500000US01015,7.5,39037,15.6,2011,Calhoun County,Not Adopted,0,2
2,Alabama,0500000US01043,5.5,40054,12.6,2011,Cullman County,Not Adopted,0,3
3,Alabama,0500000US01049,7.1,36541,19.6,2011,DeKalb County,Not Adopted,0,4
4,Alabama,0500000US01051,6.5,57405,10.6,2011,Elmore County,Not Adopted,0,5
5,Alabama,0500000US01055,4.8,33313,14.4,2011,Etowah County,Not Adopted,0,6
6,Alabama,0500000US01069,5.2,40336,13.9,2011,Houston County,Not Adopted,0,7
7,Alabama,0500000US01073,7.2,41976,13.3,2011,Jefferson County,Not Adopted,0,8
8,Alabama,0500000US01077,3.1,40121,11.0,2011,Lauderdale County,Not Adopted,0,9
9,Alabama,0500000US01081,6.4,42965,12.6,2011,Lee County,Not Adopted,0,10

In [3]:
print('Summary Statistics')

df[["uninsured", "unemployment", "median_income"]].describe()

Summary Statistics

         uninsured  unemployment  median_income
count  7380.000000   7341.000000    7380.000000
mean     10.381260      6.009767   56981.417344
std       5.094168      2.350090   15740.901841
min       1.400000      1.000000   24945.000000
25%       6.400000      4.400000   45894.750000
50%       9.600000      5.600000   53360.500000
75%      13.500000      7.200000   64381.250000
max      37.900000     21.700000  151800.000000

For the first step, I will look at the impact of Medicaid expansion on uninsured rate at the county level without pre-treatment covariates.

Briefly, the identification CS method relies on parallel trends assumption after conditioning on pre-treatment covariates. Once there is no covariates in the analysis and the comparison group is 'never treated' group, CS proposes the following causal parameter of interest (equation 2.8 in their paper).

\begin{gather*}
ATT^{nev}_{unc} (g, t) = E[Y_{t} - Y_{g  - 1}|G_{g} = 1] - E[Y_{t} - Y_{g - 1}|C = 1]
\end{gather*}  

$ATT^{nev}_{unc} (g, t)$ compares the outcome evolution of group $g$, which are the units first treated at the time $g$, between the period of time $t$ and $g$-1 with the outcome evolution of comparison group, which are never treated group, between the same time period. The outcome evolution of comparison group provides the parallel trends in case the treated group would not experienced the effect of treatment. The parameter calculates the treatment effect for group $g$ at time $t$ and it is called group-time average treatment effect.

To give an example, let's calculate $ATT_{g, t}$ for group 2014 at time 2015 using the Medicaid expansion. Group of 2014 presents the states that adopted Medicaid expansion in 2014.

\begin{gather*}
ATT(2014,2015) = (Y_{2014,2015} - Y_{2014,2013}) - (Y_{C,2015} - Y_{C, 2013})
\end{gather*} 

Let's show this in 2x2 table:

   |      | Pre(2013) | Post(2015) | Difference |
   | --- | --- | --- | --- |
   |Adopted     |  Y(2014,2013) | Y(2014,2015) |  |
   |Non-Adopted     |  Y(C, 2013) | Y(C,2015)  | |
   |**Difference**      |  |   |    |

The ATT parameter calculates the treatment effect by turning the data to a standard 2x2 DID setup with 2 groups (group of 2014 and never adopted group) and 2 time periods (2013 and 2015). Once ATT for group of 2014 is calculated for every year, it is possible to aggregate treatment effects in several ways to understand the treatment effect heterogeneity between groups.

Now I need to calculate ATT for each year for each group. For that, I need to create dummy variables for each group and treatment years for counties with Medicaid expansion.

In [4]:
## Create dummy variables for each cohort/group of treated counties.
dummies = pd.get_dummies(df, prefix='g', columns=['AdoptedYear'], drop_first= True)
df1 = pd.concat([dummies, df['AdoptedYear']],axis=1)

#Crate a dummy variable for treatment years for counties with medicaid expansion.
df1['treat'] = np.where((df1['AdoptedYear'] <= df1['year']), 1, 0)
df1.loc[df1['AdoptedYear'] == 0, 'treat'] = 0

In [5]:
df1 = df1.drop('unemployment', axis=1)

In [6]:
## Turn unbalanced data to balanced.
df1['balanced'] = df1.groupby('SID')['year'].transform('count')
df = df1[df1['balanced'] == 9]

In [7]:
## ATT estimation attempt to replicate what did package in R produces.

# function for dif-in-diff calculation.

def att(df,g,t):
    
    y11 = df[(df['MedicaidStatus'] == "Adopted") 
             & (df['AdoptedYear'] == g)
             & (df['year'] == t)]['uninsured'].mean()
             
    y10 = df[(df['MedicaidStatus'] == "Adopted") 
             & (df['AdoptedYear'] == g)
             & (df['year'] == g - 1)]['uninsured'].mean()
             
    y01 = df[(df['MedicaidStatus'] == "Not Adopted") 
             & (df['year'] == t)]['uninsured'].mean()    

    y00 = df[(df['MedicaidStatus'] == "Not Adopted") 
             & (df['year'] == g - 1)]['uninsured'].mean()
    
    did = (y11 - y10) - (y01 - y00)
    
    return did
## 
result = []
groups = df1['AdoptedYear'].unique()
times = df1['year'].unique()

for group in groups:
    if group > 0:
        for time in times:
            x = att(df, group, time)
            result.append((group,time,x))
            
att_estimate = pd.DataFrame(result)
att_estimate.columns = ['group','time', 'att']
att_estimate.sort_values(['group', 'time'])

    group  time       att
9    2014  2011 -0.165584
10   2014  2012 -0.033914
11   2014  2013  0.000000
12   2014  2014 -0.722202
13   2014  2015 -0.850385
14   2014  2016 -0.951367
15   2014  2017 -1.210256
16   2014  2018 -1.218141
17   2014  2019 -1.271070
0    2015  2011 -1.069500
1    2015  2012 -0.898858
2    2015  2013 -0.971423
3    2015  2014  0.000000
4    2015  2015 -0.271924
5    2015  2016 -0.392561
6    2015  2017 -1.108150
7    2015  2018 -1.006238
8    2015  2019 -1.224181
27   2016  2011  1.167932
28   2016  2012  0.989644
29   2016  2013 -0.272627
30   2016  2014  0.622994
31   2016  2015  0.000000
32   2016  2016 -1.004995
33   2016  2017 -3.046520
34   2016  2018 -3.793939
35   2016  2019 -3.113353
36   2018  2011 -2.409487
37   2018  2012 -1.764139
38   2018  2013 -1.639744
39   2018  2014 -0.153516
40   2018  2015  0.179853
41   2018  2016  0.056374
42   2018  2017  0.000000
43   2018  2018 -0.310147
44   2018  2019 -1.726227
18   2019  2011 -1.584341
19   2019  2012 -1.073993
20   2019  2013 -0.669597
21   2019  2014 -0.471703
22   2019  2015  0.008333
23   2019  2016 -0.678480
24   2019  2017 -0.804853
25   2019  2018  0.000000
26   2019  2019 -0.744414

Now I calculated group-time treatment affects for each group and time pair and I can calculate the aggregate ATT for each group. Before that I need to point that ATT(g,t) is zero once $t$<$g$ is. It means that ATT for time 2011, 2012, and 2013 are not considered in the aggregate ATT(g) for group of 2014.

In [8]:
att_estimate[att_estimate['time'] >= att_estimate['group']].groupby(['group'])['att'].mean()

group
2014   -1.037237
2015   -0.800611
2016   -2.739702
2018   -1.018187
2019   -0.744414
Name: att, dtype: float64

So far, I calculate group-time treatment effects and aggregate ATTs for each group. Now, I would like to check my results with R package's result which is provided by CS.

In [9]:
%%R
options(warn = -1)
install.packages("did", repos='http://cran.us.r-project.org', quiet=TRUE)
install.packages("ggplot2", repos='http://cran.us.r-project.org', quiet=TRUE)
install.packages("dplyr", repos='http://cran.us.r-project.org', quiet=TRUE)
library(did)
library(ggplot2)
library(dplyr)
df_medicaid <- read.csv('https://raw.githubusercontent.com/mehmet-sari/Exercises_Applications/main/medicaidexpansion.csv')
df_medicaid <- subset(df_medicaid, select = -c(unemployment))
df_medicaid["AdoptedYear"][df_medicaid["AdoptedYear"] == 2020] <- 0
df_medicaid["AdoptedYear"][df_medicaid["AdoptedYear"] == 2021] <- 0
att <- att_gt(yname = "uninsured",  
              tname = "year",  
              idname = "SID", 
              gname = "AdoptedYear",  
              data = df_medicaid,  
              xformla = NULL,   
              est_method = "dr", 
              control_group = "nevertreated", 
              bstrap = TRUE,  
              biters = 1000,  
              print_details = FALSE)  
summary(att)

package 'did' successfully unpacked and MD5 sums checked
package 'ggplot2' successfully unpacked and MD5 sums checked
package 'dplyr' successfully unpacked and MD5 sums checked

R[write to console]:
Attaching package: 'dplyr'


R[write to console]: The following objects are masked from 'package:stats':

    filter, lag


R[write to console]: The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Call:
att_gt(yname = "uninsured", tname = "year", idname = "SID", gname = "AdoptedYear",
    xformla = NULL, data = df_medicaid, control_group = "nevertreated",
    bstrap = TRUE, biters = 1000, est_method = "dr", print_details = FALSE)

Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.  "Difference-in-Differences with Multiple Time Periods." Forthcoming at the Journal of Econometrics <https://arxiv.org/abs/1803.09015>, 2020.

Group-Time Average Treatment Effects:
 Group Time ATT(g,t) Std. Error [95% Simult.  Conf. Band]
  2014 2012   0.1063     0.1615       -0.3668      0.5794
  2014 2013   0.0539     0.1396       -0.3552      0.4631
  2014 2014  -0.7857     0.1580       -1.2487     -0.3228 *
  2014 2015  -0.9508     0.1883       -1.5026     -0.3991 *
  2014 2016  -1.0373     0.2038       -1.6345     -0.4400 *
  2014 2017  -1.3097     0.2065       -1.9147     -0.7047 *
  2014 2018  -1.3181     0.2029       -1.9124     -0.7237 *
  2014 2019  -1.3658     0.2087       -1.9772     -0.7544 *
  2015 2012   0.1453     0.2400       -0.5579      0.8485
  2015 2013  -0.0526     0.2072       -0.6597      0.5546
  2015 2014   0.9079     0.1932        0.3418      1.4740 *
  2015 2015  -0.3088     0.1933       -0.8753      0.2576
  2015 2016  -0.4149     0.2355       -1.1048      0.2750
  2015 2017  -1.1440     0.2523       -1.8833     -0.4048 *
  2015 2018  -1.0426     0.2415       -1.7503     -0.3350 *
  2015 2019  -1.2553     0.2384       -1.9539     -0.5567 *
  2016 2012  -0.2036     0.5043       -1.6813      1.2741
  2016 2013  -1.2423     0.5600       -2.8829      0.3984
  2016 2014   0.8321     0.3127       -0.0842      1.7484
  2016 2015  -0.6599     0.4001       -1.8323      0.5124
  2016 2016  -0.9904     0.5029       -2.4640      0.4832
  2016 2017  -3.0455     0.5517       -4.6618     -1.4292 *
  2016 2018  -3.7934     0.5436       -5.3861     -2.2007 *
  2016 2019  -3.1076     0.5078       -4.5954     -1.6198 *
  2018 2012   0.6200     0.3347       -0.3605      1.6005
  2018 2013   0.1444     0.3058       -0.7515      1.0403
  2018 2014   1.4227     0.3231        0.4761      2.3693 *
  2018 2015   0.2965     0.2895       -0.5517      1.1446
  2018 2016  -0.1089     0.3815       -1.2268      1.0089
  2018 2017  -0.0699     0.3970       -1.2332      1.0934
  2018 2018  -0.3106     0.3929       -1.4618      0.8405
  2018 2019  -1.7215     0.3820       -2.8406     -0.6024 *
  2019 2012   0.4850     0.5830       -1.2231      2.1931
  2019 2013   0.4244     0.8207       -1.9802      2.8290
  2019 2014   0.1344     0.7134       -1.9559      2.2246
  2019 2015   0.4431     0.6411       -1.4352      2.3215
  2019 2016  -0.6723     0.6179       -2.4827      1.1382
  2019 2017  -0.1399     0.5335       -1.7031      1.4233
  2019 2018   0.8044     0.5349       -0.7629      2.3716
  2019 2019  -0.7392     0.4635       -2.0973      0.6189
---
Signif. codes: `*' confidence band does not cover 0

P-value for pre-test of parallel trends assumption:  0
Control Group:  Never Treated,  Anticipation Periods:  0
Estimation Method:  Doubly Robust

It seems that the results from R package for CS method are not equal to the results I calculated manually. Numbers are close, trends are similar but somehow there is a slight difference between the results. Lastly I shall check the aggregate ATT results.

In [10]:
%%R 
att <-aggte(att, type = "group")
summary(att)

Call:
aggte(MP = att, type = "group")

Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.  "Difference-in-Differences with Multiple Time Periods." Forthcoming at the Journal of Econometrics <https://arxiv.org/abs/1803.09015>, 2020.


Overall ATT:
     ATT Std. Error     [95%  Conf. Int.]
 -1.1425     0.1336   -1.4044     -0.8806 *


Group Effects:
 group     ATT Std. Error [95% Simult.  Conf. Band]
  2014 -1.1279     0.1782       -1.5588     -0.6970 *
  2015 -0.8332     0.1924       -1.2983     -0.3680 *
  2016 -2.7342     0.4471       -3.8154     -1.6531 *
  2018 -1.0161     0.3721       -1.9158     -0.1163 *
  2019 -0.7392     0.4397       -1.8025      0.3241
---
Signif. codes: `*' confidence band does not cover 0

Control Group:  Never Treated,  Anticipation Periods:  0
Estimation Method:  Doubly Robust

The table below shows the results from my code and the results from R package side by side. Again the R package and my code produce similar but not exactly same results. 

|My Code |       | R Package |    |
| :--- | ---- | :--- | ---- |
|group   |  ATT   |  group |  ATT |
|2014 |  -1.0372 | 2014 | -1.1279 | 
|2015 |  -0.8006 | 2015 | -0.8332 | 
|2016 |  -2.7397 | 2016 | -2.7342 | 
|2018 |  -1.0181 | 2018 | -1.0161 | 
|2019 |  -0.7444 | 2019 | -0.7392 | 

In the next step, I will estimate the treatment effect of Medicaid expansion with covariates. For that, I will use the following parameter which includes propensity score estimation. 

\begin{gather*}
ATT(g,t)=[(\frac{G_{g}}{E\big[G_{g}\big]} - \frac{\frac{p_{g}(X)C}{1-pg(X)}}{E\big[\frac{p_{g}(X)C}{1-p_{g}(X)}\big]})(Y_{t}-Y_{g-1})
\end{gather*}